### PR TITLE
fix(op-hardforks): update impl `Index<EthereumHardfork>` for `OpChainHardforks`

### LINKED ISSUE #65: fix(op-hardforks): update impl `Index<EthereumHardfork>` for `OpChainHardforks`
For https://github.com/paradigmxyz/reth/pull/18486#discussion_r2355118213 we need `OpChainHardforks` with:
- Paris hardfork with TTD fork condition
- Dao hardfork not activated

This is a follow-up of #64, so we may also do https://github.com/alloy-rs/hardforks/pull/64#discussion_r2350327934

### PR DESCRIPTION
**Pull request by mablr**
Closes #65 and unlocks https://github.com/paradigmxyz/reth/pull/18486

- Paris hardfork with TTD fork condition
- Dao hardfork not activated
- Replaced panic! out of bound with ForkCondition Never variant for more robustness

Related: #64

### CODE REVIEW

File: crates/op-hardforks/src/lib.rs [hunk 1]
```diff
@@ -339,15 +337,28 @@ impl Index<EthereumHardfork> for OpChainHardforks {
...
+                activation_block_number: 0,
+                fork_block: Some(0),
+                total_difficulty: U256::ZERO,
+            },
             Shanghai => &self[Canyon],
             Cancun => &self[Ecotone],
             Prague => &self[Isthmus],
-            Osaka | Bpo1 | Bpo2 | Bpo3 | Bpo4 | Bpo5 | Amsterdam => panic!("index out of bounds"),
+            // Not activated for now
+            Osaka | Bpo1 | Bpo2 | Bpo3 | Bpo4 | Bpo5 | Amsterdam => &ForkCondition::Never,
```
Comment (mablr) [inline crates/op-hardforks/src/lib.rs:361]: I think it's more robust like (cf. https://github.com/alloy-rs/hardforks/pull/64#discussion_r2350327934)

**Review by mattsse — APPROVED** [review]
lgtm
